# Generated by Django 3.1.5 on 2021-01-20 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='INVENTORY',
            fields=[
                ('Item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MOVIE',
            fields=[
                ('Movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='STORE',
            fields=[
                ('Store_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Address', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='USER',
            fields=[
                ('User_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Surname', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='RENTAL',
            fields=[
                ('ID_register', models.IntegerField(primary_key=True, serialize=False)),
                ('Checkout_date', models.DateField()),
                ('Return_date', models.DateField()),
                ('ID_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapi.inventory')),
                ('ID_store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapi.store')),
                ('ID_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapi.user')),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='ID_movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapi.movie'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='ID_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapi.store'),
        ),
    ]
